main/default/objects/Product_Information__mdt/Product_Information__mdt.object-meta.xml
<CustomObject>
    <description>Customer product Information by country</description>
    <label>Product Information</label>
    <pluralLabel>Product Information</pluralLabel>
</CustomObject>

main/default/objects/Product_Information__mdt/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <label>ATM Fee in other currencies</label>
    <length>56</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Information__mdt/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <length>56</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Information__mdt/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Information__mdt/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <label>Cost per Calendar Month</label>
    <length>56</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Information__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Germany</fullName>
                <default>true</default>
                <label>Germany</label>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductInformationController.cls
/**
 * @description This controller class for ProductInformation.LWC 
 * @author sudhakar
 */
public with sharing class ProductInformationController {
	/**
     * @description Identifies Product information for specified case's contact country
     * @param caseId Id of the case to get product info
     * @return      `List<Product_Information__mdt>`
     */
	@AuraEnabled(cacheable=true)
    public static object getProductInformation(String caseId) {
		List<Case> caseRecord = [Select Contact.Product__c, Contact.Home_Country__c FROM Case WHERE Id=:caseId LIMIT 1];
		if (caseRecord.size() == 0 || caseRecord[0].Contact.Home_Country__c == null || caseRecord[0].Contact.Product__c == null) {
			return 404;
		}
		List<Product_Information__mdt> productInfoList = [SELECT ATM_Fee_in_other_currencies__c, Card_Replacement_Cost__c, 
														  Card_Type__c, Cost_per_Calendar_Month__c, Country__c
															FROM Product_Information__mdt 
															WHERE Country__c = :caseRecord[0].Contact.Home_Country__c
															AND Card_Type__c = :caseRecord[0].Contact.Product__c 
															LIMIT 1];

		if (productInfoList.size() == 0) {
			return 404;
		}
		return productInfoList;
    }
}